version: '3'
services:
  chatbox-be:
    image: cs360-ocr:0.0.1
      #command: python3 -m uvicorn chatbox.main:app --host 0.0.0.0 --port 8080
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8082:8080
